### ISSUE TITLE
[BUG] LibsqlError: URL_INVALID: The URL 'undefined' is not in a valid format

### ISSUE THREAD

**Issue by rohanrehman** [lucasamonrc/passkeys#1]
I'm currently testing the repo... per README. Looks like there are some missing setup steps?
I do have a TURSO db setup that should probably be documented as a requirement before running.

```
LibsqlError: URL_INVALID: The URL 'undefined' is not in a valid format
    at parseUri (/Users/rohan/minilab/passkeys/node_modules/@libsql/core/lib-cjs/uri.js:12:15)
    at expandConfig (/Users/rohan/minilab/passkeys/node_modules/@libsql/core/lib-cjs/config.js:29:39)
    at createClient (/Users/rohan/minilab/passkeys/node_modules/@libsql/client/lib-cjs/node.js:28:52)
    at Object.<anonymous> (/Users/rohan/minilab/passkeys/src/database/connection.ts:6:27)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._compile (/Users/rohan/minilab/passkeys/node_modules/source-map-support/source-map-support.js:5
```
constants.ts has your credentials hard coded... This too could be a point of improvement on the docs.

```
export default {
  acceptedOrigin: process.env.ACCEPTED_ORIGIN || [
    "http://localhost:3000",
    "http://localhost:3001",
  ],
  rpId: process.env.RP_ID || "localhost",
  rpName: "@lucasamonrc:passkeys",
};

```

**Comment by lucasamonrc** [comment]
Hey Rohan! The constants.ts are not credentials to anything, just constant values I use when generating WebAuthn requests.

You error seems to be related to the Database connection. I'm using SQLite through Turso, if you check out the [example.env](./example.env) file you'll see which environment variables you'll need to set there.
